### ISSUE TITLE
[bug] Import issue with get_computers_from_domain ?

### ISSUE THREAD

**Issue by laluka** [p0dalirius/ApacheTomcatScanner#55]
Henlo !
Wanted to play with your lovely tool, ending up testing the install via pip / pipx, from pypi and sources, python 3.8 and 3.12, all suffer from the following issue, I saw the recent logs and a fix have been pushed, but may not solve ? '-'

Have a nice day ! 🌹 

```
Traceback (most recent call last):
  File "ApacheTomcatScanner.py", line 8, in <module>
    from apachetomcatscanner.__main__ import main
  File "/home/lalu/Downloads/ApacheTomcatScanner/apachetomcatscanner/__main__.py", line 16, in <module>
    from sectools.windows.ldap import get_computers_from_domain, get_servers_from_domain, get_subnets
ImportError: cannot import name 'get_computers_from_domain' from 'sectools.windows.ldap' (unknown location)
```

**Comment by laluka** [comment]
Works fine on python 3.8, thanks! 😘
